### ISSUE TITLE
Could not load media-textures

### ISSUE THREAD

**Issue by movabo** [inexor-game/code#331] opened 2016-09-21 21:58 UTC
After installing and compiling the program, downloading the data-repos into the media folder i still get the following errors (multiple times) by running the game:

```
23:48:38 [global] [warning] could not load texture media/interface/guiskin.png
23:48:38 [global] [warning] could not load texture media/interface/icon/mrfixit2.jpg
23:48:38 [global] [warning] could not load texture media/interface/guislider.png
23:48:38 [global] [warning] could not load texture media/interface/icon/menu.jpg
23:48:38 [global] [warning] could not load texture media/interface/icon/exit.jpg
23:48:38 [global] [warning] could not load texture media/interface/cursor/default.png
```

The game runs, but it is overall yellow:
![image](https://cloud.githubusercontent.com/assets/4041740/18730552/3b551c02-8057-11e6-924b-1faf95c68226.png)

**Comment by movabo** [comment] 2016-09-21 22:01
A (i guess dirty solution) is: `ln -s ./data/interface interface` (for linux obviously)

**Comment by Croydon** [comment] 2016-09-21 22:31
Each of the media repos is in a sub directory?
You used inexor_unix or inexor_unix_node to start Inexor?

**Comment by a-teammate** [comment] 2016-09-21 22:35
Remove your old settings (remove the inexor settings folder)

**Comment by movabo** [comment] 2016-09-23 23:47
@Croydon: I used inexor_unix
@a-teammate: It was a fresh installation, so i guess this should be changed somewhere in the repository as well.

**Comment by Croydon** [comment] 2016-12-18 01:19
@movabo We weren't able to reproduce this. Could you maybe try it again with a fresh git checkout of the latest master and a fresh Inexor config?

**Comment by Fohlen** [comment] 2017-02-06 00:13
Closing because it can't be reproduced and will be done differently with Flex.

**Closed by Fohlen** 2017-02-06 00:13 UTC
Labels: org:needs validation/discussion/decision
