### ISSUE TITLE
Don't bundle precompiled dynamic binaries

### ISSUE THREAD

**Issue by FaTony** [inexor-game/code#344] opened 2016-11-22 07:20 UTC
I'm trying to build Inexor on Debian Testing and here's what I get:

    /code/platform/tool/linux/gluecodegenerator: error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory

The gluecodegenerator is linked against Boost 1.58 but Debian Testing currently has Boost 1.62. I think it is a terrible idea to bundle precompiled binaries in the repo because it will lead to errors like this. I suggest to remove the binaries and to alter CMake file to compile them first.

**Comment by Croydon** [comment] 2016-11-22 10:13
This is a known issue and will be resolved with https://github.com/inexor-game/code/tree/a_teammate/conan.io

Thanks for reporting anway :)

**Comment by a-teammate** [comment] 2016-11-22 10:33
I'll just assign some Linux and osx people: we need to fix some conan packages for each (while we can safely consider osx a third class citizen, but that may change since @Fohlen is on Mac now).  
The branch is already working for Windows visual Studio (for vs 14 for sure, 12 also seems to work, but we won't try to support anything before vs 2015 aka 14, with latest updates).  Mingw is as well considered not important (not only from us but also some conan tools dont test for Mingw by default).  Could be upgraded (/problematic packages could be fixed) though.

**Comment by FaTony** [comment] 2016-11-22 14:30
That produces the following errors:
    /home/fatony/Stuff/Games/Inexor/Git/code/inexor/gluegen/parse_sourcecode.cpp: In function ‘void inexor::rpc::gluegen::handle_so_constructors(inexor::rpc::gluegen::optionclass&, const pugi::xml_node&)’:
    /home/fatony/Stuff/Games/Inexor/Git/code/inexor/gluegen/parse_sourcecode.cpp:215:66: error: invalid initialization of non-const reference of type ‘std::__cxx11::string& {aka std::__cxx11::basic_string<char>&}’ from an rvalue of type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’
             arg.default_value = parse_bracket(arg.default_value, string(), string()); //fu_cast<float>("{{index}}") -> "{{index}}"
                                                                  ^~~~~~~~
    /home/fatony/Stuff/Games/Inexor/Git/code/inexor/gluegen/parse_sourcecode.cpp:87:8: note:   initializing argument 2 of ‘std::__cxx11::string inexor::rpc::gluegen::parse_bracket(std::__cxx11::string, std::__cxx11::string&, std::__cxx11::string&)’
 string parse_bracket(string input, string &before_bracket, string &after_bracket)
        ^~~~~~~~~~~~~
    /home/fatony/Stuff/Games/Inexor/Git/code/inexor/gluegen/parse_sourcecode.cpp: In function ‘void inexor::rpc::gluegen::handle_shared_var(pugi::xml_node, std::vector<inexor::rpc::gluegen::ShTreeNode>&, std::__cxx11::string)’:
    /home/fatony/Stuff/Games/Inexor/Git/code/inexor/gluegen/parse_sourcecode.cpp:354:80: error: invalid initialization of non-const reference of type ‘std::__cxx11::string& {aka std::__cxx11::basic_string<char>&}’ from an rvalue of type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’
 ring constructor_argsstr = parse_bracket(raw_str, option.class_name, string());
                                                                      ^~~~~~~~
    /home/fatony/Stuff/Games/Inexor/Git/code/inexor/gluegen/parse_sourcecode.cpp:87:8: note:   initializing argument 3 of ‘std::__cxx11::string inexor::rpc::gluegen::parse_bracket(std::__cxx11::string, std::__cxx11::string&, std::__cxx11::string&)’
 string parse_bracket(string input, string &before_bracket, string &after_bracket)
        ^~~~~~~~~~~~~

**Comment by FaTony** [comment] 2016-11-22 14:36
I have fixed them in #345.

**Comment by FaTony** [comment] 2016-11-22 15:13
Even after building a gluegen and doing `make install` with it, it still tries to load it from /platform/tool/linux/gluecodegenerator. This makes it impossible to build without messing with repository contents.

**Comment by a-teammate** [comment] 2016-11-22 15:19
Yes, you will need the manual install step to override the gluecodegenerator in platform/../
(gluegen install command does not work good enough) 

This whole thing is fixed in the conan.io branch (we build gluegen as a separate step beforehand there)

**Comment by FaTony** [comment] 2016-11-22 15:31
Looks like #346 is basically the same as this. I don't think GNU/Linux people will mind building libprotobuf, CEF or whatever manually.

**Comment by Croydon** [comment] 2016-12-18 01:08
More or less a duplicate of #319 solved by #351.

**Closed by Croydon** 2016-12-18 01:08 UTC
Labels: cat:BUG, org:in progress, prio:BUILD FAILING
