### ISSUE TITLE
Make sure that the Chromium dev tools work

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#180] opened 2015-05-13 16:10 UTC
It should be possible to display the dev tools inside inexor.

**Comment by aschaeffer** [comment] 2015-06-13 11:38
It worked for me. You need to start Google Chrome or Chromium and connect it to the port Inexor provides.

**Comment by Croydon** [comment] 2015-06-17 11:34
What port is it?

**Comment by aschaeffer** [comment] 2015-06-17 15:41
9222
Am 17.06.2015 13:34 schrieb Michael Keck <notifications@github.com>:What port is it?

**Comment by koraa** [comment] 2015-07-12 14:22
In order to elaborate on this: It would be cool, if we could open the developer tools *within* inexor.

**Comment by Fohlen** [comment] 2016-02-19 13:06
As noticed within the CEF documentation, the CEF remote debugging port enables support for remote debugging for Chromium and/or Google Chrome. As further outlined on the Chrome documentation, the developer tools are a special set of pages composed to interact with the Browser, which is **NOT** shipped within the CEF library. Therefore we either port these tools into Inexor (which is pointless overhead), or close this issue.

**Comment by a-teammate** [comment] 2016-04-26 13:31
okay, so closing it?

**Comment by aschaeffer** [comment] 2016-04-26 14:45
yes

**Comment by Croydon** [comment] 2016-04-26 15:20
Why tagging "ui" and removing the "cef" tag? This is not an UI issue?

**Closed by Croydon** 2016-04-26 15:20 UTC
Labels: enhancement, ui

**Comment by MartinMuzatko** [comment] 2016-04-28 12:21
> Our goal is to make the game as moddable and **developer-friendly** as possible. Even though we might have refactored most of the code at some point, Inexor should always feel like Sauerbraten gameplay wise.

AFAIK, the dev tools within inexor would be a great way for finding out about bugs. This would also  make other players that are developers able to find out what the problem is and report it there. Without them needing a build/deploy system or remote debugging tool.

If it is not too much overhead I'd include it.

**Comment by Croydon** [comment] 2016-04-28 12:33
Well, in this case it's just needed to install Chromium/Chrome. I guess that is fine.
