### ISSUE TITLE
Compile error (relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC)

### ISSUE THREAD

**Issue by Lyberta** [inexor-game/code#346] opened 2016-11-22 15:27 UTC
I'm getting this when trying to build on 64 bit Debian Testing:

/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(common.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(int128.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(once.o): relocation R_X86_64_32S against symbol `_ZN6google8protobuf8internal16FunctionClosure03RunEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(status.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(stringpiece.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(arena.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(extension_set.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(generated_message_util.o): relocation R_X86_64_32 against symbol `_ZN6google8protobuf8internal17DeleteEmptyStringEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(message_lite.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(repeated_field.o): relocation R_X86_64_32 against symbol `_ZTIc@@CXXABI_1.3' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(wire_format_lite.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(coded_stream.o): relocation R_X86_64_32S against symbol `_ZNK6google8protobuf2io20ZeroCopyOutputStream14AllowsAliasingEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(zero_copy_stream.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(zero_copy_stream_impl_lite.o): relocation R_X86_64_32S against symbol `_ZTVN6google8protobuf2io16ArrayInputStreamE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(descriptor.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(descriptor_database.o): relocation R_X86_64_32S against symbol `_ZTVN6google8protobuf24MergedDescriptorDatabaseE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(descriptor.pb.o): relocation R_X86_64_32S against symbol `_ZNK6google8protobuf28UninterpretedOption_NamePart13IsInitializedEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(dynamic_message.o): relocation R_X86_64_32S against symbol `_ZN6google8protobuf15FieldDescriptor17kTypeToCppTypeMapE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(extension_set_heavy.o): relocation R_X86_64_32S against symbol `_ZN6google8protobuf15FieldDescriptor17kTypeToCppTypeMapE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(generated_message_reflection.o): relocation R_X86_64_32S against symbol `_ZTVN6google8protobuf8internal26GeneratedMessageReflectionE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(map_field.o): relocation R_X86_64_32 against symbol `_ZN6google8protobuf8internal30DeleteMapEntryDefaultInstancesEv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(message.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(reflection_ops.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(substitute.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(text_format.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(unknown_field_set.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(wire_format.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(strtod.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(tokenizer.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(zero_copy_stream_impl.o): relocation R_X86_64_32S against symbol `_ZTVN6google8protobuf2io24ConcatenatingInputStreamE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(atomicops_internals_x86_gcc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(stringprintf.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(structurally_valid.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(strutil.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(arenastring.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../platform/lib/linux-x86_64/libprotobuf.a(any.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC

**Comment by a-teammate** [comment] 2016-11-22 21:22
This one will as well be fixed with a_teammate/conan.io  (at least for protobuf, could occur for others but those errors will get eliminated by the package manager.
Ill try to push the progress on linux a bit (but it will comparable slow)

**Comment by a-teammate** [comment] 2016-11-25 19:11
okay:
branch a_teammate/conan.io could already compile on linux (but i soley got feedback from travis, where it has some ABI missmatches, probably since we have different compilers there and we don't invoke cmake with the same one as conan yet.)

could you test that branch?
* checkout the branch
* instead of cmakeing directly invoke conan:
   * `conan install <path_to_code_repo> --build`
      * you can specify additional arguments for your compiler, arch, build_type (Release or Debug) after `-s ` if you want
         * e.g. `conan install .. --build -s compiler=gcc -s compiler.libcxx=libstdc++11`
      * "--build" means compile everything from source
         * we could switch this later on.
      * (inside your build folder ofc)
* run cmake normally and build afterwards using your normal toolchain

**Comment by a-teammate** [comment] 2016-12-17 00:26
@FaTony Could you verify this is fixed for you in the newest master?

**Comment by FaTony** [comment] 2016-12-17 04:17
Still can't connect to conan.io. I've emailed the devs.

**Comment by a-teammate** [comment] 2016-12-19 19:43
I reproduced your error in the CI:
https://ci.appveyor.com/project/inexor-game/code/build/0.1475/job/9x20rdvnj5xc0eti#L115

Could be because of an unstable connection in this case though

**Comment by FaTony** [comment] 2016-12-19 22:14
That site doesn't open for me. Does it require cookies?

**Comment by FaTony** [comment] 2016-12-20 17:02
Ok, the connection problem is solved. Now I get this:

libjpeg-turbo/1.5.1@lasote/stable: ERROR: Package '203987eb97b3cca7c58e283392496f484738ee54' build failed
libjpeg-turbo/1.5.1@lasote/stable: WARN: Build folder /home/fatony/.conan/data/libjpeg-turbo/1.5.1/lasote/stable/build/203987eb97b3cca7c58e283392496f484738ee54
ERROR: libjpeg-turbo: Error 256 while executing cd libjpeg-turbo-1.5.1 && env LIBS="" LDFLAGS="    $LDFLAGS" CFLAGS="-fPIC $CFLAGS   -g  " CPPFLAGS="$CPPFLAGS   -g  " C_INCLUDE_PATH=$C_INCLUDE_PATH: CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH: ./configure

**Comment by a-teammate** [comment] 2016-12-20 17:11
Nice!
 yeah you need to install `nasm` (scroll up a bit to see the real error)

**Comment by FaTony** [comment] 2016-12-20 17:32
Alright, Conan finished. What now? If I execute `cmake ..` I get:

-- Current conanbuildinfo.cmake directory: /home/fatony/Stuff/Games/Inexor/Git/code/build
-- BUILD_TYPE: Debug
-- CMAKE_VERSION = 3.7.1
-- CMAKE_GENERATOR = Unix Makefiles
CMake Error at /usr/share/cmake-3.7/Modules/CMakeDetermineSystem.cmake:94 (message):
  Could not find toolchain file:
  /home/fatony/Stuff/Games/Inexor/Git/code/platform/linux.cmake
Call Stack (most recent call first):
  CMakeLists.txt:20 (project)


-- Configuring incomplete, errors occurred!
See also "/home/fatony/Stuff/Games/Inexor/Git/code/build/CMakeFiles/CMakeOutput.log".
See also "/home/fatony/Stuff/Games/Inexor/Git/code/build/CMakeFiles/CMakeError.log".

**Comment by a-teammate** [comment] 2016-12-20 17:55
Remove your build folder :)
For CMake: Always if you changed dependencies (or anything fails for CMake) removing the cache is probably the solution

**Comment by FaTony** [comment] 2016-12-20 18:06
Removed build folder, executed `conan install`, `cmake ..` and `make`:

    /home/fatony/.conan/data/InexorGlueGen/0.3.0alpha/inexor/testing/package/06e73f993769c6b0c2a21a431f959111143f0660/bin/gluecodegenerator: error while loading shared libraries: libgcrypt.so.11: cannot open shared object file: No such file or directory

**Comment by a-teammate** [comment] 2016-12-20 18:36
Ive no idea.
try adding 
```python

    def imports(self):
        self.copy("*.dll", dst="bin", src="bin") # From bin to bin
        self.copy("*.so*", dst="bin", src="bin") # From bin to bin //dunno
        self.copy("*.so*", dst="bin", src="lib") # From lib to bin //dunno
        self.copy("*.dylib*", dst="bin", src="lib") # From lib to bin
        self.copy("*.dylib*", dst="bin", src="bin") # From lib to bin

```
to `inexor/gluegen/conanfile.py`
and then start over from conan install on

**Comment by FaTony** [comment] 2016-12-20 18:40
Where is this file?

**Comment by a-teammate** [comment] 2016-12-21 01:52
Did you git pull? ;D

**Comment by FaTony** [comment] 2016-12-21 14:51
Same error. On GNU/Linux the executable directory is not searched by default. The library needs to be in some well known location, for example /usr/local/lib.

**Comment by a-teammate** [comment] 2016-12-25 12:51
Well ive got no idea.
Could you try to fix this?
Maybe locate the specific libs
are they next to the binary (now)? (We set the rpath so that .so files should work if placed next to the binary)
Or where are they?
(the binary in question is `gluecodegenerator` and is somewhere in your `.conan` directory
maybe compare that to the ldd output (https://stackoverflow.com/questions/50159/show-all-libraries-used-by-executables-on-linux)
maybe build with `--build` instead of `--build=missing` or try adding the `--update` flag
last but not least you could try to find out which dependency is using libgcrypt.
all deps are listed in `dependencies.py`

**Comment by FaTony** [comment] 2016-12-26 00:42
I've found the problem. `gluecodegenerator` requires `libgcrypt.so.11` but I have `libgcrypt.so.20'. I'm not sure why it was built that way.

**Comment by a-teammate** [comment] 2016-12-26 18:12
hm weird.

We still need to know which dependency brought in this libgcrypt thingy.
(Could be that its libcef.so, I'd check this one firstly with ldd)

Maybe also conanbuildinfo.cmake is giving some insights

**Comment by FaTony** [comment] 2016-12-26 18:30
libcef.so in `.conan/data/CEF/3.2704.1424.gc3f0a5b/a_teammate/testing/package/5fff42a1da84fca23d7ba5604c80d3a5bb914863/lib` requires libgcrypt.so.20

**Comment by a-teammate** [comment] 2016-12-26 20:50
Hm okay, this happens bc the only exception where we do not build the deps but download them is libcef.so ..
I'll adjust the [conanfile.py](https://www.conan.io/source/CEF/3.2704.1424.gc3f0a5b/a_teammate/testing) to replace the "Downloading CEF prebuilts from opensource.spotify.com" with the steps here: https://bitbucket.org/chromiumembedded/cef/wiki/MasterBuildQuickStart.md
This will take much longer though and requires a lot of space (8GB RAM and 40GB Disc space they sey.. :-1: )  furthmore it means we maybe need to get a solution [for all requirements of CEF](https://chromium.googlesource.com/chromium/src/+/lkgr/build/install-build-deps.sh#139)

I'll try to do this thursday

**Comment by a-teammate** [comment] 2017-01-25 17:01
OH fuck it, i didn't click the send button after writing a comment ..

> Well I didn't do this `thursday` (quote), but its really some work and I don't think I can do this sanely without being on linux myself.
> 
> Could you try building CEF from source (preferably in a chroot) and listing all commands you needed to build it?
> We need to adapt the conanfile to do exactly what you did manually then.
> 
https://hackmd.io/CYQwnCDGIwtATABjADlgFngdgIyxSourAGaKLwwCsOOARsJEA===?both

**Comment by Lyberta** [comment] 2017-01-26 07:58
Couldn't open that site, it requires tons of 3rd party requests and cookies. If you are on Windows, you can download VirtualBox and install GNU/Linux on it, that's how I learned it and was able to migrate. I may try to build CEF from source in a few days.

**Comment by a-teammate** [comment] 2017-01-26 11:05
I've also installed a lot of noscript stuff and the only thing you need to allow is stuff from the hackmd.io domain: Javascript, cookies, client rectangles. You can block everything else and it will work just fine (except for the side-on-side view and maybe the login)

**Comment by Lyberta** [comment] 2017-01-26 11:53
I've enabled only 1st party requests and here's how it looks:
![hackmd](https://cloud.githubusercontent.com/assets/10873185/22330375/620f49e4-e3df-11e6-986c-f874f2f545d1.png)

**Comment by a-teammate** [comment] 2017-01-26 19:28
the contents o the pad:

# Conan CEF package

We need to have an development version of CEF, we use the conan package manager for this.

So it needs to be cleanly buildable: all dependencies need to be the same as the ones on the developer machine (if you're prebuilding stuff, the versions of the dependencies of CEF may be different from the versions you prebuilt the deps. In case you use the very same library CEF used, but in a different version, you will run into linkage errors).

So firstly we need to build libcef (we currently just build the C++ Wrapper around it) on the dev machine.
A quick and dirty approach could then be to just use apt-get to download any dependencies one needs on the dev machine and then build libcef as described here: https://bitbucket.org/chromiumembedded/cef/wiki/MasterBuildQuickStart.md
We would just let a script execute all the commands necessary to do that on the dev machine.
Afterwards we could improve on that (since we do not really want to rely on having apt-get on the devs OS available) and cover all dependencies of libcef step by step by conan (so it would build all deps of libcef, then build libcef and afterwards inexor)


With conan we do in a python script what a developer would do by hand to build dependencies.

So bascially we could also just execute https://chromium.googlesource.com/chromium/src/+/lkgr/build/install-build-deps.sh I guess

**Comment by a-teammate** [comment] 2017-05-22 10:47
@Lyberta this was your error: https://bitbucket.org/chromiumembedded/cef/issues/1873

**Closed** 2017-06-07 13:18 UTC
Labels: cat:BUG, org:in progress, prio:BUILD FAILING

**Comment by Fohlen** [comment] 2017-06-07 13:20
Nice that this has been resolved, been watching it closely for some times now without any real clue!
