### ISSUE TITLE
Drop the terrible crypto code

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#184] opened 2015-06-10 15:05 UTC
Sauerbraten's, and thus Inexor's crypto code is terrible: It's years old, implements all primitives, protocols and even basic math libraries like Bigints or Jacobians. It has never been reviewed. It has not been updated in years. It is bound not too pass a basic cryptoanalysis.

Since this code can not provide any real cryptographic security, I suggest we simply erase it and implement something better (based on the proper libraries) at one point.

**Comment by a-teammate** [comment] 2015-06-10 15:59
the irc-log (#inexor on irc.gamesurge.net) on that issue:
<Calinou>+1
<Calinou>although, maybe don't use OpenSSL
<Calinou>but that's just me
<mapc>why not?
<a_teammate>well i think if someone is then going to reimplement the auth stuff again, he can choose what he finds the most fitting
<a_teammate>and thats probably not going to be openssl anyways
<mapc>when we do C, there basicall is a choise between openssl, libressl and gnutls
<a_teammate>polarssl
<mapc>what that?
<mapc>I mean "why polarssl"
<a_teammate>no i just meant its missing in the list
<mapc>oh, ok
<a_teammate>well i just saw it got a successor already https://tls.mbed.org/openssl-alternative
<a_teammate>"mbed TLS"
<mapc>:/
<mapc>that's a product
<mapc>https://news.ycombinator.com/item?id=7572465
<mapc>lack of support for hardware accelerated AES-GCM using AES-NI
<mapc>that matters for a game...
<mapc>The way I'd go is probably use the openssl custom transport API to implement OpenSSL for the message connects
<mapc>both gnutls and libressl support the openssl api, so we can use those
<mapc>I am not sure about mbed
<Hanni2>btw would it make sense to encrypt the network traffic? not really?
<mapc>well, that's the prime use of cryptography
<a_teammate>well, is licensing of matter?
<mapc>gpl might be a problem
<a_teammate>atm its used soley for the authkey stuff iirc
<mapc>Hanni2: and yes it does. It hardens us against a host of attacks.
<mapc>The kind of attacks pisto did against the NL some time ago would be rendered completely impossible
<Hanni2>ok
<mapc>also when someone is doing admin work, that should definitively be well authenticated and secured
<mapc>and if you are playing tournaments...

**Comment by Croydon** [comment] 2015-06-10 17:36
Duplicate of #2.

**Closed by Croydon** 2015-06-10 17:36 UTC
Labels: refactor

**Comment by koraa** [comment] 2015-06-10 18:22
it is not. It is a discussion about dropping the sauer code; #2 is about implementing a better lib.

**Comment by aschaeffer** [comment] 2015-06-10 18:24
I see no real difference between both issues, and if there is one, please extend the first issue instead of creating a very similar.

**Comment by koraa** [comment] 2015-06-10 18:29
can we drop the code?bbbbbbbb
